'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Archive, ArchiveRestore, FileScan, FileText, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { toast } from 'sonner'

interface Material { id: string; fileName: string; fileSize: number; totalPages: number; ocrPages: number; archivedAt: string | null; lastUsedAt: string | null; createdAt: string }

export default function MaterialsClient() {
  const [materials, setMaterials] = useState<Material[]>([]); const [loading, setLoading] = useState(true); const [showArchived, setShowArchived] = useState(false); const [search, setSearch] = useState('')
  async function load(archived = showArchived) { setLoading(true); try { const response = await fetch(`/api/materials?archived=${archived}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMaterials(data.materials) } catch (error) { toast.error(error instanceof Error ? error.message : 'Erro ao carregar materiais') } finally { setLoading(false) } }
  useEffect(() => { void load(showArchived) }, [showArchived])
  const filtered = useMemo(() => materials.filter((item) => item.fileName.toLocaleLowerCase('pt-BR').includes(search.trim().toLocaleLowerCase('pt-BR'))), [materials, search])
  async function rename(item: Material) { const fileName = window.prompt('Novo nome do material:', item.fileName)?.trim(); if (!fileName || fileName === item.fileName) return; await mutate(item.id, 'PATCH', { fileName }, 'Material renomeado') }
  async function archive(item: Material) { await mutate(item.id, 'PATCH', { archived: !item.archivedAt }, item.archivedAt ? 'Material restaurado' : 'Material arquivado') }
  async function remove(item: Material) { if (!window.confirm(`Excluir permanentemente “${item.fileName}”? Os simulados já criados serão mantidos, mas o PDF processado não poderá ser reutilizado.`)) return; await mutate(item.id, 'DELETE', undefined, 'Material excluído') }
  async function mutate(id: string, method: 'PATCH' | 'DELETE', body: object | undefined, success: string) { const response = await fetch(`/api/materials/${id}`, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) return toast.error(data.error || 'Não foi possível alterar o material'); toast.success(success); await load() }
  return <div className="mx-auto max-w-7xl p-5 pb-24 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-700">Conteúdo reutilizável</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Meus materiais</h1><p className="mt-2 text-slate-600">Seus PDFs processados ficam disponíveis para criar novos simulados sem novo envio.</p></div><Link href="/dashboard/novo" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-5 py-3 font-black text-white"><Plus className="h-5 w-5" /> Adicionar material</Link></div>
    <section className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3.5 h-5 w-5 text-slate-400" /><span className="sr-only">Buscar material</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar pelo nome do PDF" className="w-full rounded-xl border border-slate-300 py-3 pl-11 pr-4 outline-none focus:ring-2 focus:ring-blue-600" /></label><button onClick={() => setShowArchived((value) => !value)} className={`rounded-xl border px-4 py-3 text-sm font-black ${showArchived ? 'border-blue-300 bg-blue-50 text-blue-700' : 'border-slate-300'}`}>{showArchived ? 'Ocultar arquivados' : 'Mostrar arquivados'}</button></section>
    {loading ? <div className="mt-10 text-center font-bold text-slate-500">Carregando materiais...</div> : filtered.length ? <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <article key={item.id} className={`rounded-3xl border bg-white p-5 shadow-sm ${item.archivedAt ? 'border-slate-200 opacity-70' : 'border-blue-100'}`}><div className="flex items-start justify-between gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-red-50 text-red-600">{item.ocrPages ? <FileScan className="h-6 w-6" /> : <FileText className="h-6 w-6" />}</span>{item.archivedAt && <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">Arquivado</span>}</div><h2 className="mt-4 truncate text-lg font-black" title={item.fileName}>{item.fileName}</h2><p className="mt-2 text-sm text-slate-500">{item.totalPages} páginas · {(item.fileSize / 1024 / 1024).toFixed(2)} MB</p><p className="mt-1 text-xs text-slate-400">{item.ocrPages ? `OCR usado em ${item.ocrPages} página(s)` : 'Texto digital extraído'}</p><div className="mt-5 flex flex-wrap gap-2">{!item.archivedAt && <Link href={`/dashboard/novo?material=${item.id}`} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white">Criar simulado</Link>}<button onClick={() => rename(item)} className="rounded-xl border border-slate-300 p-2.5" aria-label="Renomear"><Pencil className="h-4 w-4" /></button><button onClick={() => archive(item)} className="rounded-xl border border-slate-300 p-2.5" aria-label={item.archivedAt ? 'Restaurar' : 'Arquivar'}>{item.archivedAt ? <ArchiveRestore className="h-4 w-4" /> : <Archive className="h-4 w-4" />}</button><button onClick={() => remove(item)} className="rounded-xl border border-red-200 p-2.5 text-red-600" aria-label="Excluir"><Trash2 className="h-4 w-4" /></button></div></article>)}</section> : <section className="mt-7 rounded-3xl border border-slate-200 bg-white p-12 text-center"><FileText className="mx-auto h-12 w-12 text-blue-600" /><h2 className="mt-4 text-xl font-black">Nenhum material encontrado</h2><p className="mt-2 text-slate-600">Envie um PDF no criador de simulados para adicioná-lo à biblioteca.</p></section>}
  </div>
}
